import React, { useState } from "react";
import {
  CheckCircle2,
  Shield,
  Scale,
  ChevronRight,
  Calculator,
  MapPin,
  Bookmark,
  Info,
  Award,
  Clock,
  Sparkles,
  HelpCircle
} from "lucide-react";
import { useNavigate } from "react-router-dom";

export default function SchemeCard({
  scheme,
  onCheckEligibility,
  onToggleCompare,
  isCompared = false,
  isMostSuitable = false,
  onShowBreakdown,
  onSaveScheme,
  isSaved = false,
  onCalculateEMI,
  onFindPartner
}) {
  const navigate = useNavigate();
  const [localSaved, setLocalSaved] = useState(isSaved);

  const matchScore = scheme.matchScore !== undefined ? scheme.matchScore : 85;
  const isHighMatch = matchScore >= 80;
  const eligibilityStatus = scheme.eligibilityStatus || (matchScore >= 75 ? "Eligible" : "Partially Matching");

  const maxLoanDisplay = scheme.maxLoanAmount || scheme.maxLoan || 500000;
  const interestRateDisplay = scheme.interestRate || (scheme.subsidyRate ? scheme.subsidyRate.split("+")[0] : "Concessional");
  const moratoriumDisplay = scheme.moratorium || "Up to 6 Months";
  const repaymentDisplay = scheme.repaymentPeriod || (scheme.tenureMonths ? `${scheme.tenureMonths} Months` : "36 to 60 Months");

  // Fallback transparent reasons if not already generated by engine
  const displayReasons = scheme.reasons && scheme.reasons.length > 0 ? scheme.reasons : [
    "Social category is eligible for priority assistance",
    "Loan requirement matches scheme limits",
    "Business enterprise type is supported"
  ];

  const handleSaveToggle = (e) => {
    e.stopPropagation();
    const nextState = !localSaved;
    setLocalSaved(nextState);
    if (onSaveScheme) {
      onSaveScheme(scheme, nextState);
    }
  };

  const handleCalculateEMI = () => {
    if (onCalculateEMI) {
      onCalculateEMI(scheme);
    } else {
      navigate(`/calculator?amount=${maxLoanDisplay}`);
    }
  };

  const handleFindPartner = () => {
    if (onFindPartner) {
      onFindPartner(scheme);
    } else {
      navigate("/partners");
    }
  };

  return (
    <div
      className={`group bg-white rounded-3xl border transition-all duration-300 flex flex-col justify-between text-left relative overflow-hidden ${
        isMostSuitable
          ? "border-saarthi-green ring-2 ring-emerald-500/20 shadow-hover bg-gradient-to-b from-emerald-50/20 via-white to-white"
          : "border-slate-200 hover:border-slate-300 shadow-card hover:shadow-hover"
      }`}
    >
      {/* Top Border Indicator */}
      {isMostSuitable && (
        <div className="bg-gradient-to-r from-emerald-500 via-saarthi-green to-emerald-600 h-1.5 w-full" />
      )}

      <div className="p-5 sm:p-6 flex-1 flex flex-col">
        {/* Most Suitable Badge / Top Ribbon */}
        <div className="flex items-center justify-between gap-2 mb-3">
          {isMostSuitable ? (
            <div className="inline-flex items-center space-x-1.5 px-3 py-1 rounded-full bg-saarthi-green text-white text-[11px] font-black shadow-xs tracking-wide">
              <Award className="w-3.5 h-3.5 text-amber-300" />
              <span>MOST SUITABLE MATCH</span>
            </div>
          ) : (
            <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block">
              {scheme.ministry || scheme.category || "Government Support Scheme"}
            </span>
          )}

          {/* Save Scheme Bookmark */}
          <button
            type="button"
            onClick={handleSaveToggle}
            title={localSaved ? "Saved to Bookmarks" : "Save Scheme"}
            className={`p-1.5 rounded-xl border transition ${
              localSaved
                ? "bg-amber-50 border-amber-300 text-amber-600"
                : "bg-slate-50 hover:bg-slate-100 border-slate-200 text-slate-400 hover:text-slate-600"
            }`}
          >
            <Bookmark className={`w-4 h-4 ${localSaved ? "fill-amber-500 text-amber-500" : ""}`} />
          </button>
        </div>

        {/* Scheme Title & Status */}
        <div className="flex items-start justify-between gap-3 mb-2">
          <h3 className="text-lg font-black text-saarthi-navy group-hover:text-saarthi-navy-light transition-colors leading-snug">
            {scheme.name}
          </h3>

          {/* Match Score Badge */}
          <div className="flex flex-col items-end flex-shrink-0">
            <div
              className={`px-2.5 py-1 rounded-xl text-xs font-black flex items-center space-x-1 ${
                isHighMatch
                  ? "bg-emerald-100 text-emerald-900 border border-emerald-300"
                  : "bg-blue-100 text-blue-900 border border-blue-200"
              }`}
            >
              <Sparkles className="w-3 h-3 text-amber-500" />
              <span>{matchScore}% Match</span>
            </div>
            <span
              className={`text-[10px] font-bold mt-1 px-2 py-0.5 rounded-full ${
                eligibilityStatus === "Eligible"
                  ? "bg-emerald-50 text-emerald-700"
                  : eligibilityStatus === "Partially Matching"
                  ? "bg-amber-50 text-amber-700"
                  : "bg-red-50 text-red-700"
              }`}
            >
              {eligibilityStatus}
            </span>
          </div>
        </div>

        {/* Short Description */}
        <p className="text-xs text-slate-600 leading-relaxed line-clamp-2 mb-4">
          {scheme.shortDescription || scheme.overview}
        </p>

        {/* Key Financial Terms Grid */}
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 p-3 rounded-2xl bg-slate-50 border border-slate-100 mb-4 text-xs">
          <div>
            <span className="text-[10px] text-slate-400 font-bold uppercase block">Max Loan</span>
            <strong className="text-saarthi-navy font-bold text-xs truncate block">
              ₹{Number(maxLoanDisplay).toLocaleString("en-IN")}
            </strong>
          </div>

          <div>
            <span className="text-[10px] text-slate-400 font-bold uppercase block">Interest Rate</span>
            <strong className="text-saarthi-green font-bold text-xs truncate block">
              {interestRateDisplay}
            </strong>
          </div>

          <div>
            <span className="text-[10px] text-slate-400 font-bold uppercase block">Moratorium</span>
            <strong className="text-slate-700 font-semibold text-xs truncate block">
              {moratoriumDisplay}
            </strong>
          </div>

          <div>
            <span className="text-[10px] text-slate-400 font-bold uppercase block">Repayment</span>
            <strong className="text-slate-700 font-semibold text-xs truncate block">
              {repaymentDisplay}
            </strong>
          </div>
        </div>

        {/* "Why this scheme?" Transparent Reasons */}
        <div className="p-3.5 rounded-2xl bg-emerald-50/50 border border-emerald-100 mb-4">
          <div className="flex items-center justify-between mb-2">
            <span className="text-[11px] font-black uppercase tracking-wider text-emerald-950 flex items-center space-x-1">
              <CheckCircle2 className="w-3.5 h-3.5 text-saarthi-green" />
              <span>Why this scheme?</span>
            </span>

            {/* "Why am I seeing this?" Button */}
            {onShowBreakdown && (
              <button
                type="button"
                onClick={() => onShowBreakdown(scheme)}
                className="text-[10px] font-bold text-saarthi-navy hover:text-saarthi-green underline flex items-center space-x-0.5"
              >
                <span>Why am I seeing this?</span>
              </button>
            )}
          </div>

          <ul className="space-y-1.5 text-xs text-slate-700">
            {displayReasons.slice(0, 4).map((r, idx) => (
              <li key={idx} className="flex items-start space-x-1.5 text-[11px] leading-tight">
                <span className="text-saarthi-green font-bold flex-shrink-0">✓</span>
                <span className="text-slate-700 font-medium">{r}</span>
              </li>
            ))}
          </ul>
        </div>

        {/* Target Demographics Tags */}
        <div className="flex flex-wrap gap-1 mb-4">
          {(scheme.targetDemographic || scheme.eligibleSocialCategories || []).slice(0, 4).map((tag) => (
            <span
              key={tag}
              className="px-2 py-0.5 rounded-md bg-slate-100 text-slate-600 text-[10px] font-medium"
            >
              {tag}
            </span>
          ))}
        </div>

        {/* Data Trust & Prototype Footnote */}
        <div className="pt-2 border-t border-slate-100 mb-3 text-[10px] text-slate-400 flex flex-wrap items-center justify-between gap-1">
          <span>Status: <strong className="text-slate-600">{scheme.verificationStatus ? "Demo Data" : "Demo Data"}</strong></span>
          <span>Updated: {scheme.lastUpdated || "September 2026"}</span>
          <span className="truncate max-w-[200px]" title={scheme.source || "Government Scheme Prototype Data"}>
            Source: {scheme.source ? scheme.source.slice(0, 28) + "..." : "Official Framework"}
          </span>
        </div>
      </div>

      {/* Card Action Controls & Buttons */}
      <div className="px-5 pb-5 pt-1 flex flex-col gap-2.5">
        <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
          {/* View Details */}
          <button
            type="button"
            onClick={() => onCheckEligibility && onCheckEligibility(scheme)}
            className="w-full py-2 px-2.5 rounded-xl bg-slate-100 hover:bg-slate-200 text-saarthi-navy text-xs font-bold transition flex items-center justify-center space-x-1 shadow-xs"
          >
            <span>View Details</span>
            <ChevronRight className="w-3.5 h-3.5" />
          </button>

          {/* Calculate EMI */}
          <button
            type="button"
            onClick={handleCalculateEMI}
            className="w-full py-2 px-2.5 rounded-xl bg-blue-50 hover:bg-blue-100 text-blue-900 text-xs font-bold transition flex items-center justify-center space-x-1 border border-blue-200"
          >
            <Calculator className="w-3.5 h-3.5 text-blue-700" />
            <span>Calculate EMI</span>
          </button>

          {/* Find Nearby Partner */}
          <button
            type="button"
            onClick={handleFindPartner}
            className="w-full py-2 px-2.5 rounded-xl bg-amber-50 hover:bg-amber-100 text-amber-900 text-xs font-bold transition flex items-center justify-center space-x-1 border border-amber-200"
          >
            <MapPin className="w-3.5 h-3.5 text-amber-700" />
            <span>Find Partner</span>
          </button>

          {/* Check Eligibility / Primary Action */}
          <button
            type="button"
            onClick={() => onCheckEligibility && onCheckEligibility(scheme)}
            className="w-full py-2 px-2.5 rounded-xl bg-saarthi-green hover:bg-saarthi-green-hover text-white text-xs font-bold transition shadow-sm flex items-center justify-center space-x-1"
          >
            <span>Check Criteria</span>
          </button>
        </div>

        {/* Compare Toggle & Disclaimer */}
        <div className="flex items-center justify-between text-[11px] text-slate-500 pt-1">
          <label className="flex items-center space-x-1.5 cursor-pointer select-none">
            <input
              type="checkbox"
              checked={isCompared}
              onChange={() => onToggleCompare && onToggleCompare(scheme)}
              className="w-3.5 h-3.5 accent-saarthi-navy rounded cursor-pointer"
            />
            <span className="font-semibold text-slate-700">Compare with others</span>
          </label>

          <span className="text-[10px] text-slate-400 italic">
            Verify final eligibility with authority
          </span>
        </div>
      </div>
    </div>
  );
}
